// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metadata.proto

package hraftkv;

public final class Metadata {
  private Metadata() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code hraftkv.MetadataType}
   */
  public enum MetadataType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>META_UNKNOWN = 0;</code>
     */
    META_UNKNOWN(0, 0),
    /**
     * <code>META_SESSION_ID = 1;</code>
     */
    META_SESSION_ID(1, 1),
    ;

    /**
     * <code>META_UNKNOWN = 0;</code>
     */
    public static final int META_UNKNOWN_VALUE = 0;
    /**
     * <code>META_SESSION_ID = 1;</code>
     */
    public static final int META_SESSION_ID_VALUE = 1;


    public final int getNumber() { return value; }

    public static MetadataType valueOf(int value) {
      switch (value) {
        case 0: return META_UNKNOWN;
        case 1: return META_SESSION_ID;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MetadataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MetadataType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MetadataType>() {
            public MetadataType findValueByNumber(int number) {
              return MetadataType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return hraftkv.Metadata.getDescriptor().getEnumTypes().get(0);
    }

    private static final MetadataType[] VALUES = values();

    public static MetadataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MetadataType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:hraftkv.MetadataType)
  }

  public interface SessionIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hraftkv.SessionId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string ip = 1;</code>
     */
    boolean hasIp();
    /**
     * <code>required string ip = 1;</code>
     */
    java.lang.String getIp();
    /**
     * <code>required string ip = 1;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>required int64 lease_time = 2;</code>
     */
    boolean hasLeaseTime();
    /**
     * <code>required int64 lease_time = 2;</code>
     */
    long getLeaseTime();
  }
  /**
   * Protobuf type {@code hraftkv.SessionId}
   */
  public static final class SessionId extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hraftkv.SessionId)
      SessionIdOrBuilder {
    // Use SessionId.newBuilder() to construct.
    private SessionId(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SessionId(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SessionId defaultInstance;
    public static SessionId getDefaultInstance() {
      return defaultInstance;
    }

    public SessionId getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SessionId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              ip_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              leaseTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hraftkv.Metadata.internal_static_hraftkv_SessionId_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hraftkv.Metadata.internal_static_hraftkv_SessionId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hraftkv.Metadata.SessionId.class, hraftkv.Metadata.SessionId.Builder.class);
    }

    public static com.google.protobuf.Parser<SessionId> PARSER =
        new com.google.protobuf.AbstractParser<SessionId>() {
      public SessionId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SessionId(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SessionId> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int IP_FIELD_NUMBER = 1;
    private java.lang.Object ip_;
    /**
     * <code>required string ip = 1;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ip = 1;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEASE_TIME_FIELD_NUMBER = 2;
    private long leaseTime_;
    /**
     * <code>required int64 lease_time = 2;</code>
     */
    public boolean hasLeaseTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 lease_time = 2;</code>
     */
    public long getLeaseTime() {
      return leaseTime_;
    }

    private void initFields() {
      ip_ = "";
      leaseTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLeaseTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIpBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, leaseTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIpBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, leaseTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static hraftkv.Metadata.SessionId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hraftkv.Metadata.SessionId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hraftkv.Metadata.SessionId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hraftkv.Metadata.SessionId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hraftkv.Metadata.SessionId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hraftkv.Metadata.SessionId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hraftkv.Metadata.SessionId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hraftkv.Metadata.SessionId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hraftkv.Metadata.SessionId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hraftkv.Metadata.SessionId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hraftkv.Metadata.SessionId prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hraftkv.SessionId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hraftkv.SessionId)
        hraftkv.Metadata.SessionIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hraftkv.Metadata.internal_static_hraftkv_SessionId_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hraftkv.Metadata.internal_static_hraftkv_SessionId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hraftkv.Metadata.SessionId.class, hraftkv.Metadata.SessionId.Builder.class);
      }

      // Construct using hraftkv.Metadata.SessionId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        leaseTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hraftkv.Metadata.internal_static_hraftkv_SessionId_descriptor;
      }

      public hraftkv.Metadata.SessionId getDefaultInstanceForType() {
        return hraftkv.Metadata.SessionId.getDefaultInstance();
      }

      public hraftkv.Metadata.SessionId build() {
        hraftkv.Metadata.SessionId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hraftkv.Metadata.SessionId buildPartial() {
        hraftkv.Metadata.SessionId result = new hraftkv.Metadata.SessionId(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.leaseTime_ = leaseTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hraftkv.Metadata.SessionId) {
          return mergeFrom((hraftkv.Metadata.SessionId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hraftkv.Metadata.SessionId other) {
        if (other == hraftkv.Metadata.SessionId.getDefaultInstance()) return this;
        if (other.hasIp()) {
          bitField0_ |= 0x00000001;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasLeaseTime()) {
          setLeaseTime(other.getLeaseTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIp()) {
          
          return false;
        }
        if (!hasLeaseTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hraftkv.Metadata.SessionId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hraftkv.Metadata.SessionId) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object ip_ = "";
      /**
       * <code>required string ip = 1;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ip = 1;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ip = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip = 1;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 1;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 1;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ip_ = value;
        onChanged();
        return this;
      }

      private long leaseTime_ ;
      /**
       * <code>required int64 lease_time = 2;</code>
       */
      public boolean hasLeaseTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 lease_time = 2;</code>
       */
      public long getLeaseTime() {
        return leaseTime_;
      }
      /**
       * <code>required int64 lease_time = 2;</code>
       */
      public Builder setLeaseTime(long value) {
        bitField0_ |= 0x00000002;
        leaseTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 lease_time = 2;</code>
       */
      public Builder clearLeaseTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        leaseTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hraftkv.SessionId)
    }

    static {
      defaultInstance = new SessionId(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hraftkv.SessionId)
  }

  public interface RaftGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hraftkv.RaftGroup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional bytes start_key = 2;</code>
     */
    boolean hasStartKey();
    /**
     * <code>optional bytes start_key = 2;</code>
     */
    com.google.protobuf.ByteString getStartKey();

    /**
     * <code>optional bytes end_key = 3;</code>
     */
    boolean hasEndKey();
    /**
     * <code>optional bytes end_key = 3;</code>
     */
    com.google.protobuf.ByteString getEndKey();

    /**
     * <code>required string conf = 4;</code>
     */
    boolean hasConf();
    /**
     * <code>required string conf = 4;</code>
     */
    java.lang.String getConf();
    /**
     * <code>required string conf = 4;</code>
     */
    com.google.protobuf.ByteString
        getConfBytes();

    /**
     * <code>optional string initial_priority = 5;</code>
     */
    boolean hasInitialPriority();
    /**
     * <code>optional string initial_priority = 5;</code>
     */
    java.lang.String getInitialPriority();
    /**
     * <code>optional string initial_priority = 5;</code>
     */
    com.google.protobuf.ByteString
        getInitialPriorityBytes();

    /**
     * <code>optional int64 initial_leader_priority = 6;</code>
     */
    boolean hasInitialLeaderPriority();
    /**
     * <code>optional int64 initial_leader_priority = 6;</code>
     */
    long getInitialLeaderPriority();
  }
  /**
   * Protobuf type {@code hraftkv.RaftGroup}
   */
  public static final class RaftGroup extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hraftkv.RaftGroup)
      RaftGroupOrBuilder {
    // Use RaftGroup.newBuilder() to construct.
    private RaftGroup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RaftGroup(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RaftGroup defaultInstance;
    public static RaftGroup getDefaultInstance() {
      return defaultInstance;
    }

    public RaftGroup getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RaftGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              startKey_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              endKey_ = input.readBytes();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              conf_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              initialPriority_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              initialLeaderPriority_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hraftkv.Metadata.internal_static_hraftkv_RaftGroup_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hraftkv.Metadata.internal_static_hraftkv_RaftGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hraftkv.Metadata.RaftGroup.class, hraftkv.Metadata.RaftGroup.Builder.class);
    }

    public static com.google.protobuf.Parser<RaftGroup> PARSER =
        new com.google.protobuf.AbstractParser<RaftGroup>() {
      public RaftGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RaftGroup(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RaftGroup> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_KEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString startKey_;
    /**
     * <code>optional bytes start_key = 2;</code>
     */
    public boolean hasStartKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes start_key = 2;</code>
     */
    public com.google.protobuf.ByteString getStartKey() {
      return startKey_;
    }

    public static final int END_KEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString endKey_;
    /**
     * <code>optional bytes end_key = 3;</code>
     */
    public boolean hasEndKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes end_key = 3;</code>
     */
    public com.google.protobuf.ByteString getEndKey() {
      return endKey_;
    }

    public static final int CONF_FIELD_NUMBER = 4;
    private java.lang.Object conf_;
    /**
     * <code>required string conf = 4;</code>
     */
    public boolean hasConf() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string conf = 4;</code>
     */
    public java.lang.String getConf() {
      java.lang.Object ref = conf_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          conf_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string conf = 4;</code>
     */
    public com.google.protobuf.ByteString
        getConfBytes() {
      java.lang.Object ref = conf_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INITIAL_PRIORITY_FIELD_NUMBER = 5;
    private java.lang.Object initialPriority_;
    /**
     * <code>optional string initial_priority = 5;</code>
     */
    public boolean hasInitialPriority() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string initial_priority = 5;</code>
     */
    public java.lang.String getInitialPriority() {
      java.lang.Object ref = initialPriority_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          initialPriority_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string initial_priority = 5;</code>
     */
    public com.google.protobuf.ByteString
        getInitialPriorityBytes() {
      java.lang.Object ref = initialPriority_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        initialPriority_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INITIAL_LEADER_PRIORITY_FIELD_NUMBER = 6;
    private long initialLeaderPriority_;
    /**
     * <code>optional int64 initial_leader_priority = 6;</code>
     */
    public boolean hasInitialLeaderPriority() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 initial_leader_priority = 6;</code>
     */
    public long getInitialLeaderPriority() {
      return initialLeaderPriority_;
    }

    private void initFields() {
      id_ = "";
      startKey_ = com.google.protobuf.ByteString.EMPTY;
      endKey_ = com.google.protobuf.ByteString.EMPTY;
      conf_ = "";
      initialPriority_ = "";
      initialLeaderPriority_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasConf()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, startKey_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, endKey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getConfBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getInitialPriorityBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, initialLeaderPriority_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, startKey_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, endKey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getConfBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getInitialPriorityBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, initialLeaderPriority_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static hraftkv.Metadata.RaftGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hraftkv.Metadata.RaftGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hraftkv.Metadata.RaftGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hraftkv.Metadata.RaftGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hraftkv.Metadata.RaftGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hraftkv.Metadata.RaftGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hraftkv.Metadata.RaftGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hraftkv.Metadata.RaftGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hraftkv.Metadata.RaftGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hraftkv.Metadata.RaftGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hraftkv.Metadata.RaftGroup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hraftkv.RaftGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hraftkv.RaftGroup)
        hraftkv.Metadata.RaftGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hraftkv.Metadata.internal_static_hraftkv_RaftGroup_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hraftkv.Metadata.internal_static_hraftkv_RaftGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hraftkv.Metadata.RaftGroup.class, hraftkv.Metadata.RaftGroup.Builder.class);
      }

      // Construct using hraftkv.Metadata.RaftGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        startKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        endKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        conf_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        initialPriority_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        initialLeaderPriority_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hraftkv.Metadata.internal_static_hraftkv_RaftGroup_descriptor;
      }

      public hraftkv.Metadata.RaftGroup getDefaultInstanceForType() {
        return hraftkv.Metadata.RaftGroup.getDefaultInstance();
      }

      public hraftkv.Metadata.RaftGroup build() {
        hraftkv.Metadata.RaftGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hraftkv.Metadata.RaftGroup buildPartial() {
        hraftkv.Metadata.RaftGroup result = new hraftkv.Metadata.RaftGroup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.startKey_ = startKey_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.endKey_ = endKey_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.conf_ = conf_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.initialPriority_ = initialPriority_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.initialLeaderPriority_ = initialLeaderPriority_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hraftkv.Metadata.RaftGroup) {
          return mergeFrom((hraftkv.Metadata.RaftGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hraftkv.Metadata.RaftGroup other) {
        if (other == hraftkv.Metadata.RaftGroup.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasStartKey()) {
          setStartKey(other.getStartKey());
        }
        if (other.hasEndKey()) {
          setEndKey(other.getEndKey());
        }
        if (other.hasConf()) {
          bitField0_ |= 0x00000008;
          conf_ = other.conf_;
          onChanged();
        }
        if (other.hasInitialPriority()) {
          bitField0_ |= 0x00000010;
          initialPriority_ = other.initialPriority_;
          onChanged();
        }
        if (other.hasInitialLeaderPriority()) {
          setInitialLeaderPriority(other.getInitialLeaderPriority());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasConf()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hraftkv.Metadata.RaftGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hraftkv.Metadata.RaftGroup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString startKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes start_key = 2;</code>
       */
      public boolean hasStartKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes start_key = 2;</code>
       */
      public com.google.protobuf.ByteString getStartKey() {
        return startKey_;
      }
      /**
       * <code>optional bytes start_key = 2;</code>
       */
      public Builder setStartKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        startKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes start_key = 2;</code>
       */
      public Builder clearStartKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        startKey_ = getDefaultInstance().getStartKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString endKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes end_key = 3;</code>
       */
      public boolean hasEndKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes end_key = 3;</code>
       */
      public com.google.protobuf.ByteString getEndKey() {
        return endKey_;
      }
      /**
       * <code>optional bytes end_key = 3;</code>
       */
      public Builder setEndKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        endKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes end_key = 3;</code>
       */
      public Builder clearEndKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        endKey_ = getDefaultInstance().getEndKey();
        onChanged();
        return this;
      }

      private java.lang.Object conf_ = "";
      /**
       * <code>required string conf = 4;</code>
       */
      public boolean hasConf() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string conf = 4;</code>
       */
      public java.lang.String getConf() {
        java.lang.Object ref = conf_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            conf_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string conf = 4;</code>
       */
      public com.google.protobuf.ByteString
          getConfBytes() {
        java.lang.Object ref = conf_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          conf_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string conf = 4;</code>
       */
      public Builder setConf(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        conf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string conf = 4;</code>
       */
      public Builder clearConf() {
        bitField0_ = (bitField0_ & ~0x00000008);
        conf_ = getDefaultInstance().getConf();
        onChanged();
        return this;
      }
      /**
       * <code>required string conf = 4;</code>
       */
      public Builder setConfBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        conf_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object initialPriority_ = "";
      /**
       * <code>optional string initial_priority = 5;</code>
       */
      public boolean hasInitialPriority() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string initial_priority = 5;</code>
       */
      public java.lang.String getInitialPriority() {
        java.lang.Object ref = initialPriority_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            initialPriority_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string initial_priority = 5;</code>
       */
      public com.google.protobuf.ByteString
          getInitialPriorityBytes() {
        java.lang.Object ref = initialPriority_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          initialPriority_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string initial_priority = 5;</code>
       */
      public Builder setInitialPriority(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        initialPriority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string initial_priority = 5;</code>
       */
      public Builder clearInitialPriority() {
        bitField0_ = (bitField0_ & ~0x00000010);
        initialPriority_ = getDefaultInstance().getInitialPriority();
        onChanged();
        return this;
      }
      /**
       * <code>optional string initial_priority = 5;</code>
       */
      public Builder setInitialPriorityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        initialPriority_ = value;
        onChanged();
        return this;
      }

      private long initialLeaderPriority_ ;
      /**
       * <code>optional int64 initial_leader_priority = 6;</code>
       */
      public boolean hasInitialLeaderPriority() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 initial_leader_priority = 6;</code>
       */
      public long getInitialLeaderPriority() {
        return initialLeaderPriority_;
      }
      /**
       * <code>optional int64 initial_leader_priority = 6;</code>
       */
      public Builder setInitialLeaderPriority(long value) {
        bitField0_ |= 0x00000020;
        initialLeaderPriority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 initial_leader_priority = 6;</code>
       */
      public Builder clearInitialLeaderPriority() {
        bitField0_ = (bitField0_ & ~0x00000020);
        initialLeaderPriority_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hraftkv.RaftGroup)
    }

    static {
      defaultInstance = new RaftGroup(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hraftkv.RaftGroup)
  }

  public interface GroupTableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hraftkv.GroupTable)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int64 version = 1;</code>
     */
    long getVersion();

    /**
     * <code>required int32 shard_index = 2;</code>
     */
    boolean hasShardIndex();
    /**
     * <code>required int32 shard_index = 2;</code>
     */
    int getShardIndex();

    /**
     * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
     */
    java.util.List<hraftkv.Metadata.RaftGroup> 
        getGroupsList();
    /**
     * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
     */
    hraftkv.Metadata.RaftGroup getGroups(int index);
    /**
     * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
     */
    int getGroupsCount();
    /**
     * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
     */
    java.util.List<? extends hraftkv.Metadata.RaftGroupOrBuilder> 
        getGroupsOrBuilderList();
    /**
     * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
     */
    hraftkv.Metadata.RaftGroupOrBuilder getGroupsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code hraftkv.GroupTable}
   */
  public static final class GroupTable extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hraftkv.GroupTable)
      GroupTableOrBuilder {
    // Use GroupTable.newBuilder() to construct.
    private GroupTable(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GroupTable(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GroupTable defaultInstance;
    public static GroupTable getDefaultInstance() {
      return defaultInstance;
    }

    public GroupTable getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GroupTable(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              shardIndex_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                groups_ = new java.util.ArrayList<hraftkv.Metadata.RaftGroup>();
                mutable_bitField0_ |= 0x00000004;
              }
              groups_.add(input.readMessage(hraftkv.Metadata.RaftGroup.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          groups_ = java.util.Collections.unmodifiableList(groups_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hraftkv.Metadata.internal_static_hraftkv_GroupTable_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hraftkv.Metadata.internal_static_hraftkv_GroupTable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hraftkv.Metadata.GroupTable.class, hraftkv.Metadata.GroupTable.Builder.class);
    }

    public static com.google.protobuf.Parser<GroupTable> PARSER =
        new com.google.protobuf.AbstractParser<GroupTable>() {
      public GroupTable parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroupTable(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GroupTable> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private long version_;
    /**
     * <code>required int64 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 version = 1;</code>
     */
    public long getVersion() {
      return version_;
    }

    public static final int SHARD_INDEX_FIELD_NUMBER = 2;
    private int shardIndex_;
    /**
     * <code>required int32 shard_index = 2;</code>
     */
    public boolean hasShardIndex() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 shard_index = 2;</code>
     */
    public int getShardIndex() {
      return shardIndex_;
    }

    public static final int GROUPS_FIELD_NUMBER = 3;
    private java.util.List<hraftkv.Metadata.RaftGroup> groups_;
    /**
     * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
     */
    public java.util.List<hraftkv.Metadata.RaftGroup> getGroupsList() {
      return groups_;
    }
    /**
     * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
     */
    public java.util.List<? extends hraftkv.Metadata.RaftGroupOrBuilder> 
        getGroupsOrBuilderList() {
      return groups_;
    }
    /**
     * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
     */
    public int getGroupsCount() {
      return groups_.size();
    }
    /**
     * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
     */
    public hraftkv.Metadata.RaftGroup getGroups(int index) {
      return groups_.get(index);
    }
    /**
     * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
     */
    public hraftkv.Metadata.RaftGroupOrBuilder getGroupsOrBuilder(
        int index) {
      return groups_.get(index);
    }

    private void initFields() {
      version_ = 0L;
      shardIndex_ = 0;
      groups_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasShardIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getGroupsCount(); i++) {
        if (!getGroups(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, shardIndex_);
      }
      for (int i = 0; i < groups_.size(); i++) {
        output.writeMessage(3, groups_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, shardIndex_);
      }
      for (int i = 0; i < groups_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, groups_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static hraftkv.Metadata.GroupTable parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hraftkv.Metadata.GroupTable parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hraftkv.Metadata.GroupTable parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hraftkv.Metadata.GroupTable parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hraftkv.Metadata.GroupTable parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hraftkv.Metadata.GroupTable parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hraftkv.Metadata.GroupTable parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hraftkv.Metadata.GroupTable parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hraftkv.Metadata.GroupTable parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hraftkv.Metadata.GroupTable parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hraftkv.Metadata.GroupTable prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hraftkv.GroupTable}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hraftkv.GroupTable)
        hraftkv.Metadata.GroupTableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hraftkv.Metadata.internal_static_hraftkv_GroupTable_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hraftkv.Metadata.internal_static_hraftkv_GroupTable_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hraftkv.Metadata.GroupTable.class, hraftkv.Metadata.GroupTable.Builder.class);
      }

      // Construct using hraftkv.Metadata.GroupTable.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGroupsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        shardIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (groupsBuilder_ == null) {
          groups_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          groupsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hraftkv.Metadata.internal_static_hraftkv_GroupTable_descriptor;
      }

      public hraftkv.Metadata.GroupTable getDefaultInstanceForType() {
        return hraftkv.Metadata.GroupTable.getDefaultInstance();
      }

      public hraftkv.Metadata.GroupTable build() {
        hraftkv.Metadata.GroupTable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hraftkv.Metadata.GroupTable buildPartial() {
        hraftkv.Metadata.GroupTable result = new hraftkv.Metadata.GroupTable(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.shardIndex_ = shardIndex_;
        if (groupsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            groups_ = java.util.Collections.unmodifiableList(groups_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.groups_ = groups_;
        } else {
          result.groups_ = groupsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hraftkv.Metadata.GroupTable) {
          return mergeFrom((hraftkv.Metadata.GroupTable)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hraftkv.Metadata.GroupTable other) {
        if (other == hraftkv.Metadata.GroupTable.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasShardIndex()) {
          setShardIndex(other.getShardIndex());
        }
        if (groupsBuilder_ == null) {
          if (!other.groups_.isEmpty()) {
            if (groups_.isEmpty()) {
              groups_ = other.groups_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureGroupsIsMutable();
              groups_.addAll(other.groups_);
            }
            onChanged();
          }
        } else {
          if (!other.groups_.isEmpty()) {
            if (groupsBuilder_.isEmpty()) {
              groupsBuilder_.dispose();
              groupsBuilder_ = null;
              groups_ = other.groups_;
              bitField0_ = (bitField0_ & ~0x00000004);
              groupsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGroupsFieldBuilder() : null;
            } else {
              groupsBuilder_.addAllMessages(other.groups_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasShardIndex()) {
          
          return false;
        }
        for (int i = 0; i < getGroupsCount(); i++) {
          if (!getGroups(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hraftkv.Metadata.GroupTable parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hraftkv.Metadata.GroupTable) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long version_ ;
      /**
       * <code>required int64 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 version = 1;</code>
       */
      public long getVersion() {
        return version_;
      }
      /**
       * <code>required int64 version = 1;</code>
       */
      public Builder setVersion(long value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0L;
        onChanged();
        return this;
      }

      private int shardIndex_ ;
      /**
       * <code>required int32 shard_index = 2;</code>
       */
      public boolean hasShardIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 shard_index = 2;</code>
       */
      public int getShardIndex() {
        return shardIndex_;
      }
      /**
       * <code>required int32 shard_index = 2;</code>
       */
      public Builder setShardIndex(int value) {
        bitField0_ |= 0x00000002;
        shardIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 shard_index = 2;</code>
       */
      public Builder clearShardIndex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        shardIndex_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<hraftkv.Metadata.RaftGroup> groups_ =
        java.util.Collections.emptyList();
      private void ensureGroupsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          groups_ = new java.util.ArrayList<hraftkv.Metadata.RaftGroup>(groups_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          hraftkv.Metadata.RaftGroup, hraftkv.Metadata.RaftGroup.Builder, hraftkv.Metadata.RaftGroupOrBuilder> groupsBuilder_;

      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public java.util.List<hraftkv.Metadata.RaftGroup> getGroupsList() {
        if (groupsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(groups_);
        } else {
          return groupsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public int getGroupsCount() {
        if (groupsBuilder_ == null) {
          return groups_.size();
        } else {
          return groupsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public hraftkv.Metadata.RaftGroup getGroups(int index) {
        if (groupsBuilder_ == null) {
          return groups_.get(index);
        } else {
          return groupsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public Builder setGroups(
          int index, hraftkv.Metadata.RaftGroup value) {
        if (groupsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupsIsMutable();
          groups_.set(index, value);
          onChanged();
        } else {
          groupsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public Builder setGroups(
          int index, hraftkv.Metadata.RaftGroup.Builder builderForValue) {
        if (groupsBuilder_ == null) {
          ensureGroupsIsMutable();
          groups_.set(index, builderForValue.build());
          onChanged();
        } else {
          groupsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public Builder addGroups(hraftkv.Metadata.RaftGroup value) {
        if (groupsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupsIsMutable();
          groups_.add(value);
          onChanged();
        } else {
          groupsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public Builder addGroups(
          int index, hraftkv.Metadata.RaftGroup value) {
        if (groupsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupsIsMutable();
          groups_.add(index, value);
          onChanged();
        } else {
          groupsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public Builder addGroups(
          hraftkv.Metadata.RaftGroup.Builder builderForValue) {
        if (groupsBuilder_ == null) {
          ensureGroupsIsMutable();
          groups_.add(builderForValue.build());
          onChanged();
        } else {
          groupsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public Builder addGroups(
          int index, hraftkv.Metadata.RaftGroup.Builder builderForValue) {
        if (groupsBuilder_ == null) {
          ensureGroupsIsMutable();
          groups_.add(index, builderForValue.build());
          onChanged();
        } else {
          groupsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public Builder addAllGroups(
          java.lang.Iterable<? extends hraftkv.Metadata.RaftGroup> values) {
        if (groupsBuilder_ == null) {
          ensureGroupsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, groups_);
          onChanged();
        } else {
          groupsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public Builder clearGroups() {
        if (groupsBuilder_ == null) {
          groups_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          groupsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public Builder removeGroups(int index) {
        if (groupsBuilder_ == null) {
          ensureGroupsIsMutable();
          groups_.remove(index);
          onChanged();
        } else {
          groupsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public hraftkv.Metadata.RaftGroup.Builder getGroupsBuilder(
          int index) {
        return getGroupsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public hraftkv.Metadata.RaftGroupOrBuilder getGroupsOrBuilder(
          int index) {
        if (groupsBuilder_ == null) {
          return groups_.get(index);  } else {
          return groupsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public java.util.List<? extends hraftkv.Metadata.RaftGroupOrBuilder> 
           getGroupsOrBuilderList() {
        if (groupsBuilder_ != null) {
          return groupsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(groups_);
        }
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public hraftkv.Metadata.RaftGroup.Builder addGroupsBuilder() {
        return getGroupsFieldBuilder().addBuilder(
            hraftkv.Metadata.RaftGroup.getDefaultInstance());
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public hraftkv.Metadata.RaftGroup.Builder addGroupsBuilder(
          int index) {
        return getGroupsFieldBuilder().addBuilder(
            index, hraftkv.Metadata.RaftGroup.getDefaultInstance());
      }
      /**
       * <code>repeated .hraftkv.RaftGroup groups = 3;</code>
       */
      public java.util.List<hraftkv.Metadata.RaftGroup.Builder> 
           getGroupsBuilderList() {
        return getGroupsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          hraftkv.Metadata.RaftGroup, hraftkv.Metadata.RaftGroup.Builder, hraftkv.Metadata.RaftGroupOrBuilder> 
          getGroupsFieldBuilder() {
        if (groupsBuilder_ == null) {
          groupsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              hraftkv.Metadata.RaftGroup, hraftkv.Metadata.RaftGroup.Builder, hraftkv.Metadata.RaftGroupOrBuilder>(
                  groups_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          groups_ = null;
        }
        return groupsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:hraftkv.GroupTable)
    }

    static {
      defaultInstance = new GroupTable(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hraftkv.GroupTable)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hraftkv_SessionId_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hraftkv_SessionId_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hraftkv_RaftGroup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hraftkv_RaftGroup_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hraftkv_GroupTable_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hraftkv_GroupTable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016metadata.proto\022\007hraftkv\"+\n\tSessionId\022\n" +
      "\n\002ip\030\001 \002(\t\022\022\n\nlease_time\030\002 \002(\003\"\204\001\n\tRaftG" +
      "roup\022\n\n\002id\030\001 \002(\t\022\021\n\tstart_key\030\002 \001(\014\022\017\n\007e" +
      "nd_key\030\003 \001(\014\022\014\n\004conf\030\004 \002(\t\022\030\n\020initial_pr" +
      "iority\030\005 \001(\t\022\037\n\027initial_leader_priority\030" +
      "\006 \001(\003\"V\n\nGroupTable\022\017\n\007version\030\001 \002(\003\022\023\n\013" +
      "shard_index\030\002 \002(\005\022\"\n\006groups\030\003 \003(\0132\022.hraf" +
      "tkv.RaftGroup*5\n\014MetadataType\022\020\n\014META_UN" +
      "KNOWN\020\000\022\023\n\017META_SESSION_ID\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hraftkv_SessionId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hraftkv_SessionId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hraftkv_SessionId_descriptor,
        new java.lang.String[] { "Ip", "LeaseTime", });
    internal_static_hraftkv_RaftGroup_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hraftkv_RaftGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hraftkv_RaftGroup_descriptor,
        new java.lang.String[] { "Id", "StartKey", "EndKey", "Conf", "InitialPriority", "InitialLeaderPriority", });
    internal_static_hraftkv_GroupTable_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_hraftkv_GroupTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hraftkv_GroupTable_descriptor,
        new java.lang.String[] { "Version", "ShardIndex", "Groups", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
